spring:
  application:
    name: shaverma-cloud

  data:
    mongodb:
      host: localhost
      port: 27017
      database: shavermadb
      username: admin
      password: mongopass123
      authentication-database: admin
      auto-index-creation: true

# Server
server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG